default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: eveota_development

test:
  <<: *default
  database: eveota_test

production:
  <<: *default
  database: eveota_production
  username: eveota
  password: <%= ENV['EVEOTA_DATABASE_PASSWORD'] %>
